### PR TITLE
Added compatibilty in build.gradle to use buildTools etc. from projects build.gradle

### PR DESCRIPTION
**Pull request by shubham56**
Added external injection of build versions

### CODE REVIEW

**Comment by lufinkey** [comment]
This seems to break the build process. I get the following error:
```
Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by shubham56** [comment]
This is for gradle version >3.0.0
```Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html```

**Comment by lufinkey** [comment]
You should probably change the gradle version in build.gradle, then

**Comment by shubham56** [comment]
I have the gradle version and default dependencies.

**Pull request closed without merging**
