### PR TITLE
Add Ability to Set Volume

### PR DESCRIPTION
**Pull request by dcvz**
This PR adds the ability to set volume by implementing a custom audio controller

### CODE REVIEW

**Comment by lufinkey** [comment]
Hey thanks for this fix. Just want to let you know that I've seen the PR but haven't had the chance to fully review it yet.

**Comment by dcvz** [comment]
Hi @lufinkey have you had a chance to look at this?

**Comment by lufinkey** [comment]
Sorry not yet. I'm likely going to pull it in and have it be manually enabled via an initialize option until I can get some time to test it. That way you can still use it, but people can still opt out if it's causing issues

**Comment by dcvz** [comment]
What about now @lufinkey ?

**Comment by lufinkey** [comment]
I apologize for taking so long to merge this but I've just had too many things going on. Thank you for taking the time to implement this feature. Just to be on the safe side, I've made this an optional feature that can be manually enabled with `{"android":{"useCustomTrackController":true}}` in the `initialize` options.

Again, thank you for taking the time to implement this feature.

**Comment by karltaylor** [comment]
Does this work for ios?

**Pull request merged**
