### PR TITLE
Add brief description and example for token swap/refresh

### PR DESCRIPTION
**Pull request by yamalight**
As discussed in https://github.com/lufinkey/react-native-spotify/issues/22, I've added short description that mentiones how swap and refresh URLs are used. 
I've also added a very basic example server implementation that shows how handle that.
Let me know if that looks good or you want any changes 😄

### CODE REVIEW

**Comment by lufinkey** [comment]
Additionally, the refresh token needs to be encrypted and decrypted by the server. See example [here](https://github.com/lufinkey/spotify-token-refresh-php). It might also be helpful to include in the README that the CLIENT_ID and CLIENT_SECRET are set through environment variables, as some people might not realize that additional setup is required just by looking at the code.

Maybe consider adding a separate README to the example-server folder? I can open an issue for this and add you to it if you want.

**Comment by lufinkey** [comment]
Actually I'll just use the already open issue

**Comment by yamalight** [comment]
@lufinkey hm, that's a good idea. I've omitted encryption to keep the example simple, but probably it's worth adding 🤔

**Comment by lufinkey** [comment]
Yeah it is part of the OAuth standard. It could also be worth mentioning that it's part of the OAuth process and link to some examples of what OAuth is. Let's move this discussion to the open issue though

**Pull request merged**
