### PR TITLE
Support code auth on iOS via client secret

### PR DESCRIPTION
**Pull request by cabelitos**
This commit adds the support for code authentication without
the necessity of using a remote server. #This is very insecure since
Using this approach is not secure, however for testing it should
be enough.

### CODE REVIEW

**Comment by cabelitos** [comment]
sorry, wrong repo.

**Comment by lufinkey** [comment]
Hey, if you still want to merge this, I think this is useful functionality to have. Refresh servers are super annoying and I'd rather just let people do this if they want

**Comment by lufinkey** [comment]
@cabelitos

**Comment by cabelitos** [comment]
@lufinkey it's up to you. For me it's OK to merge. I did this change, because the project that I was working on had to support this feature ASAP. However the BE team was not able to implement this in time.

Do you think that I need to change something in the code? 

Ty for the support

**Comment by lufinkey** [comment]
I haven't had a chance to look through all the code, but ideally we'd want the option to include the clientSecret, but have it fall back on the current behavior if none is given

**Comment by lufinkey** [comment]
@cabelitos mind reopening this though?

**Pull request closed without merging**
